version: '3.8'
services:
  users-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"
    volumes:
      - users-data:/deployments/data
      - ./logs:/deployments/logs
    networks:
      - users-network

volumes:
  users-data:

networks:
  users-network:
    driver: bridge
